[package]
name = "core"
version.workspace = true
edition.workspace = true

[dependencies]
rusqlite = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
uuid = { workspace = true }
toml = { workspace = true }
hostname = { workspace = true }
sysinfo = { workspace = true }
